# -*- coding: utf-8 -*-
"""CSP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wd7FttMM-oR-QiYPm2ZWZ3MwKMMfNFPe
"""

from itertools import permutations

def solve_cryptarithmetic():
    for perm in permutations(range(10), 8):
        S, E, N, D, M, O, R, Y = perm

        # Check for leading zeros
        TYPE THE CODE HERE USING IF
            continue

        # Check the equation constraints
        SEND = 1000 * S + 100 * E + 10 * N + D
        MORE = 1000 * M + 100 * O + 10 * R + E
        MONEY = 10000 * M + 1000 * O + 100 * N + 10 * E + Y

        if SEND + MORE == MONEY:
            return SEND, MORE, MONEY

    return None

solution = TYPE THE CODE HERE #CALL THE FUNCTION

if solution:
    SEND, MORE, MONEY = solution
    print(f'SEND = {SEND}')
    print(f'MORE = {MORE}')
    print(f'MONEY = {MONEY}')
else:
    print("No solution found.")